use_frameworks!

target 'Demo' do
  pod 'Alloy', :path => '../'
  pod 'Alloy/Shaders', :path => '../'
end

target 'AlloyTests' do
  pod 'Alloy', :path => '../'
end

target 'DemoApp' do
  pod 'Alloy', :path => '../'
end

target 'DemoAppTests' do
  pod 'Alloy', :path => '../'
end
